#! /bin/sh

#checkout files

git --work-tree = https://github.com/sbansal-cnn/deploy-github-hook/blob/cac7909b0b9aea228b297118c1cad55da2fb9128/test --https://github.com/sbansal-cnn/deploy-github-hook/blob/cac7909b0b9aea228b297118c1cad55da2fb9128/test checkout


